user:
  max_name: 50
  max_email: 255
  min_pass: 6
  per_page: 10
micropost:
  max_content: 140
  per_page: 10
remember_me: "1"
gravatar:
  size_default: 80
  size_50: 50
  size_30: 30
feed:
  per_page: 5
image:
  file_exten: "image/jpeg,image/gif,image/png"
time_expire: 2
max_size_image: 1
